### ISSUE TITLE
Astikor Carts "pig-crash" Issue tracker

### ISSUE THREAD

**Issue by xFirefalconx** [xFirefalconx/Royal-Equines-Petrified-Magic#20]
- [ ] Apotheosis incompatibility - cannot be added. dev informed, waiting for reply.
- [ ] Tumbleweeds - was removed from pack to mend the issue - reconsider?

**Comment by xFirefalconx** [comment]
- [ ] Bug is mendable, need to find out what TFC fork author did to fix it - not gotten a reply yet (might not get any)

**Comment by xFirefalconx** [comment]
Fixed. 
https://www.curseforge.com/minecraft/mc-mods/astikorcarts-horse-carts-pigcrash-fix-fork

Hopefully I didn't break anything by applying those changes.
